version: '3.3'
services:
  database:
    image: postgres:15.3-alpine
    container_name: app_db
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=WJvlcsKMGdTDl0lWAwclEX6LFtyfQwfg
      - POSTGRES_DB=app_db
      - TZ=Americas/Sao_Paulo
    ports:
      - '5432:5432'
    volumes:
      - app_database_vm:/var/lib/postgresql/data
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0.amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0.amd64
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  app_database_vm:
