name: Running tests

on:
  pull_request:
    branches: ['develop', 'main']

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and run tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn test:cov
